name: swiftui-sandbox
options:
  deploymentTarget:
    iOS: '17.0'
  platform: iOS
  disableBundleAccessors: true
  createIntermediateGroups: true

configs:
  Debug: debug
  Release: release

settings:
  base:
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTED_INTERFACE_ORIENTATIONS: UIInterfaceOrientationPortrait
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    SWIFT_VERSION: 6.0
  configs:
    Debug:
      PRODUCT_BUNDLE_IDENTIFIER: com.lq.sandbox.dev
      BUNDLE_DISPLAY_NAME: SUI Sandbox Dev
    Release:
      PRODUCT_BUNDLE_IDENTIFIER: com.lq.sandbox
      BUNDLE_DISPLAY_NAME: SUI Sandbox

schemes:
  Debug:
    build:
      targets:
        main: all
        tests: all
    test:
      targets:
        - name: tests 
    run:
      config: Debug
  Release:
    build:
      targets:
        main: all
        tests: all
    test:
      targets:
        - name: tests
    run:
      config: Release
    archive:
      config: Release
    profile:
      config: Release

targets:
  main:
    type: application
    platform: iOS
    sources: [Source]
    resources: [Source/resources]
    settings:
      GENERATE_INFOPLIST_FILE: YES
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        CODE_SIGN_ENTITLEMENTS: Source/resources/main.entitlements
        # DEVELOPMENT_TEAM: "66Q5RW6PQQ"
    # dependencies:
    # - package: Alamofire
    # - package: ApexyAlamofire
    # - package: Apexy

  tests:
    type: bundle.unit-test
    platform: iOS
    sources: [Tests]
    dependencies:
      - target: main
    settings:
      GENERATE_INFOPLIST_FILE: YES
      base:
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        # DEVELOPMENT_TEAM: "66Q5RW6PQQ"

# packages:
#   Alamofire:
#     url: https://github.com/Alamofire/Alamofire.git
#     from: 5.5.0
#   Apexy:
#     url: https://github.com/RedMadRobot/apexy-ios.git
#     version: 1.7.2
#   ApexyAlamofire:
#     url: https://github.com/RedMadRobot/apexy-ios.git
#     version: 1.7.2